gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#33b1ff'
      - bold
    inactiveBorderColor:
      - '#5b5b5b'
    optionsTextColor:
      - '#78a9ff'
    selectedLineBgColor:
      - '#292929'
    cherryPickedCommitBgColor:
      - '#3f3f3f'
    cherryPickedCommitFgColor:
      - '#be95ff'
    unstagedChangesColor:
      - '#ee5396'
    defaultFgColor:
      - '#f3f3f3'
    searchingActiveBorderColor:
      - '#42be65'

    authorColors:
      '*': '#82cfff'
