set -g default-shell /bin/zsh

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

set -s escape-time 0
set -g status-position top
set -g window-status-separator ""
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

setw -g automatic-rename on
setw -g automatic-rename-format "#{pane_current_command}"
setw -g allow-rename off

set -g prefix C-Space

bind 1 if-shell "tmux select-window -t ':1'" '' "new-window -t 1"
bind 2 if-shell "tmux select-window -t ':2'" '' "new-window -t 2"
bind 3 if-shell "tmux select-window -t ':3'" '' "new-window -t 3"
bind 4 if-shell "tmux select-window -t ':4'" '' "new-window -t 4"
bind 5 if-shell "tmux select-window -t ':5'" '' "new-window -t 5"
bind 6 if-shell "tmux select-window -t ':6'" '' "new-window -t 6"
bind 7 if-shell "tmux select-window -t ':7'" '' "new-window -t 7"
bind 8 if-shell "tmux select-window -t ':8'" '' "new-window -t 8"
bind 9 if-shell "tmux select-window -t ':9'" '' "new-window -t 9"

set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'erikw/tmux-powerline'

set -g @catppuccin_flavor 'mocha'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'"
run '~/.tmux/plugins/tpm/tpm'
